### ISSUE TITLE
Readme link in Grav is set to develop, should be master

### ISSUE THREAD

**Issue by dbryar** [jackbrycesmith/grav-plugin-proposal#2]
Current link points to **develop**:
https://github.com/jackbrycesmith/grav-plugin-proposal/blob/develop/README.md

> 404 - Not found

Should be **master**:
https://github.com/jackbrycesmith/grav-plugin-proposal/blob/master/README.md

**Comment by jackbrycesmith** [comment]
Nice catch cheers!
